-------------------------------------------------------------------------------
Test set: in.jabezraja.captain.TestCreateTask
-------------------------------------------------------------------------------
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.1 s <<< FAILURE! - in in.jabezraja.captain.TestCreateTask
in.jabezraja.captain.TestCreateTask.testCreateTaskWithValidInput()  Time elapsed: 0.074 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: in.jabezraja.captain.exception.ValidationException: Due date should be in future
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3135)
	at in.jabezraja.captain.TestCreateTask.testCreateTaskWithValidInput(TestCreateTask.java:25)
Caused by: in.jabezraja.captain.exception.ValidationException: Due date should be in future
	at in.jabezraja.captain.service.TaskService.create(TaskService.java:30)
	at in.jabezraja.captain.TestCreateTask.lambda$testCreateTaskWithValidInput$0(TestCreateTask.java:26)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 16 more

